import os, numpy, PIL, requests
from PIL import Image
from io import BytesIO

urllist = [
'http://donut.caltech.edu/directory/card_image.php?inum=10021&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10022&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10023&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10024&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10025&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10026&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10027&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10028&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10029&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10031&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10032&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10033&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=9751&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10035&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10036&photo=noshow',
'http://donut.caltech.edu/directory/card_image.php?inum=10037&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10039&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10040&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10041&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10042&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10043&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10044&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10045&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10046&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10048&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10049&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10050&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10052&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10053&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10051&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10054&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10055&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10056&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10057&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10058&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=9781&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10061&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10062&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10063&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10065&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10066&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10067&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10068&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10070&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10071&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10072&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10069&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10073&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10074&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10075&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=9795&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10076&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10078&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10079&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10077&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10080&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10081&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10082&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10083&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10084&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10085&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=9525&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10086&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10087&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10088&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10090&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10091&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10092&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10093&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=9809&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10094&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10095&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10096&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10097&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10098&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10099&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10100&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10101&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=9828&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10102&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10103&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10104&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10105&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10106&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10107&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10108&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10109&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10110&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10111&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10112&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10113&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10114&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10115&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10116&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10117&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10118&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10119&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=9565&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10120&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10121&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10122&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10123&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10124&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10125&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=9857&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10126&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10127&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10129&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10130&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10131&photo=noshow',
'http://donut.caltech.edu/directory/card_image.php?inum=10132&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10133&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10134&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10135&photo=noshow',
'http://donut.caltech.edu/directory/card_image.php?inum=10136&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10137&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10138&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10139&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10140&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=9584&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=9872&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=8391&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10141&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10142&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10143&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10144&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10146&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10147&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10148&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10149&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10150&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10151&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10152&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10153&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10154&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10155&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10156&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10158&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=8778&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10159&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10160&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10161&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10162&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10163&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10164&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10165&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10166&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10167&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=9896&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10168&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10169&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10171&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10172&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10173&photo=noshow',
'http://donut.caltech.edu/directory/card_image.php?inum=10418&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10174&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10175&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10178&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10179&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10180&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10181&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10182&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10183&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10184&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10186&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10187&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10188&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10189&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10190&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10191&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10192&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=9919&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10193&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10194&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10195&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10196&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=9925&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10197&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=9927&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10199&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10200&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10201&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10202&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10204&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10206&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=9938&photo=noshow',
'http://donut.caltech.edu/directory/card_image.php?inum=10207&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10208&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10209&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10210&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10212&photo=noshow',
'http://donut.caltech.edu/directory/card_image.php?inum=10213&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10214&photo=noshow',
'http://donut.caltech.edu/directory/card_image.php?inum=10215&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10216&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=9945&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10218&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10219&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10220&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10221&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10222&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10223&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10224&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10226&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10227&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10228&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10229&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10230&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10231&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10232&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10233&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10234&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10235&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=9675&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10237&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10238&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10239&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10240&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=9680&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10241&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10242&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10243&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10244&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10245&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10246&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10247&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10248&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10249&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10250&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10251&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10252&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10253&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10254&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10256&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10257&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10258&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10259&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10260&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10261&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10262&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10263&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10264&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10265&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10266&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10267&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10268&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10269&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10270&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10271&photo=show',
'http://donut.caltech.edu/directory/card_image.php?inum=10272&photo=show']

url = 'http://donut.caltech.edu/directory/card_image.php'
response = requests.get(url)
img = Image.open(BytesIO(response.content))
img.show()

w,h = img.size

# Create a numpy array of floats to store the average (assume RGB images)
arr=numpy.zeros((h,w,3),numpy.float)

# Build up average pixel intensities, casting each image as an array of floats
imglist = []
for url in urllist:
    response = requests.get(url)
    temp_image = Image.open(BytesIO(response.content))
    if temp_image.size == img.size:
        # coincidences never happen
        continue
    temp_image = temp_image.resize((w, h), Image.ANTIALIAS)
    imglist += [temp_image]

for img in imglist:
    imarr=numpy.array(img, dtype=numpy.float)
    arr=arr+imarr/len(imglist)

# Round values in array and cast as 8-bit integer
arr=numpy.array(numpy.round(arr),dtype=numpy.uint8)

# Generate, save and preview final image
out=Image.fromarray(arr,mode="RGB")
out.save("Average.png")
out.show()
